FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root

# Expose MySQL port
EXPOSE 3306

# Run the MySQL server
CMD ["mysqld"]

# docker run -d --name mysql_container --network vmdb_network mysql