# @package __global__

datasource:
  max_channels: 2
  max_sample_rate: 32000

  train: /home/es119256/dados/repos/vmdb/14. Baselines/GVMGen/dataset/snes_mvdb_jsonl/train
  valid: /home/es119256/dados/repos/vmdb/14. Baselines/GVMGen/dataset/snes_mvdb_jsonl/eval
  evaluate: /home/es119256/dados/repos/vmdb/14. Baselines/GVMGen/dataset/snes_mvdb_jsonl/test
  generate: /home/es119256/dados/repos/vmdb/14. Baselines/GVMGen/dataset/snes_mvdb_jsonl/test
