# based on clap_consistency.py

import os
import json
import argparse
import typing as tp

import torch
import torchmetrics

from imagebind import data
from imagebind.models import imagebind_model
from imagebind.models.imagebind_model import ModalityType

import pandas as pd
from tqdm import tqdm

class VideoConsistencyMetric(torchmetrics.Metric):
    """Video consistency metric measuring consistency between audio and video pairs."""

    def update(self, audio: torch.Tensor, video: torch.Tensor) -> None:
        raise NotImplementedError("implement how to update the metric from the audio and video pairs.")

    def compute(self):
        raise NotImplementedError("implement how to compute the final metric score.")

class ImgBindVideoConsistencyMetric(VideoConsistencyMetric):
    """Video consistency metric relying on ImageBind.

    As a joint audio-video embedding model, a pretrained ImageBind model can be used to quantify the
    similarity between audio-video pairs. We compute the ImageBind embeddings from the videos as
    well as the generated audio based on them, and define the MCC metric as the average cosine similarity
    between these embeddings.

    Model implementation & pre-trained checkpoints: https://github.com/facebookresearch/ImageBind
    """
    def __init__(self):
        super().__init__()

        self.add_state("cosine_sum", default=torch.tensor(0.), dist_reduce_fx="sum")
        self.add_state("weight", default=torch.tensor(0.), dist_reduce_fx="sum")
        self._initialize_model()

    def _initialize_model(self):
        self.model = imagebind_model.imagebind_huge(pretrained=True)
        self.model.eval()
        self.model.cuda()

    def update(self, audios_paths: tp.List[str], videos_path: tp.List[str]) -> None:
        """Compute cosine similarity between audio and video pairs and accumulate scores over the dataset."""
        assert len(audios_paths) == len(videos_path), "Number of audio and video samples should match"

        inputs = {
            ModalityType.VISION: data.load_and_transform_video_data(videos_path, "cuda"),
            ModalityType.AUDIO: data.load_and_transform_audio_data(audios_paths, "cuda")
        }

        with torch.no_grad():
            embeddings = self.model(inputs)

        audio_embeddings = embeddings[ModalityType.AUDIO]
        video_embeddings = embeddings[ModalityType.VISION]

        # cosine similarity between the video and the audio embedding
        cosine_sim = torch.nn.functional.cosine_similarity(audio_embeddings, video_embeddings, dim=1, eps=1e-8).cpu()
        self.cosine_sum += cosine_sim.sum(dim=0)
        self.weight += torch.tensor(cosine_sim.size(0))

    def compute(self):
        """Computes the average cosine similarty across all audio/video pairs."""
        assert self.weight.item() > 0, "Unable to compute with total number of comparisons <= 0"  # type: ignore
        return (self.cosine_sum / self.weight).item()  # type: ignore


def run_img_bind_standalone():
    """
        Standalone ImageBind Score for csv generated by enabeling evaluate.metrics.save_eval_gen
    """
    # Parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('--eval_path', type=str, required=True, help="path for the eval xp folder. /eval_gen/pred_to_orig.csv are automatically added")
    parser.add_argument('--dataset_path', type=str, default="/home/es119256/dados/datasets/vmdb/nintendo-snes-spc", help="path for the snes mvdb dataset games folder")
    args = parser.parse_args()

    csv_path = os.path.join(args.eval_path, 'eval_gen/pred_to_orig.csv') 

    img_bind = ImgBindVideoConsistencyMetric()
    df = pd.read_csv(csv_path)

    for row in tqdm(df.itertuples(index=False, name=None), total=len(df)):
        y_pred_path, y_path, y_seek, json_path = row

        with open(json_path, 'r') as f:
            json_file = json.load(f)

            mp3_path = json_file["path"]
            mp3_stem = mp3_path.split('/')[-1].split('.')[0]
            game = mp3_path.split('nintendo-snes-spc/')[-1].split('/')[0]
            soundtrack = mp3_stem.split(f'{game}_')[-1]

            pt_path = json_file["visual_content"]
            video_file = pt_path.split('/')[-1].split('.')[0] + '.mp4'

            video_path = os.path.join(args.dataset_path, game, 'videos', soundtrack, video_file)

        img_bind.update([y_pred_path+'.wav'], [video_path])
    
    metric_value = img_bind.compute()

    print(f"\nImageBind Score: {metric_value}\n")

if __name__ == "__main__":
    run_img_bind_standalone()