default:
  dora_dir: /home/es119256/dados/xps/audiocraft_gvmgen
  partitions:
    global: debug
    team: debug
  reference_dir: /home/es119256/dados/xps/audiocraft_gvmgen
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: /home/es119256/dados/xps/audiocraft_gvmgen
  partitions:
    global: debug
    team: debug
  reference_dir: /home/es119256/dados/xps/audiocraft_gvmgen
