version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: db
    init: true
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=dejavu
      - MYSQL_USER=dejavu
      - MYSQL_PASSWORD=mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
volumes:
  dbdata:
